name: "hola mundo"
on:
  workflow_distpach:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: "22"
      - name: "saludo js"
        run: "node index.js"